
sndsys.com:  start.obj shell.obj codec.obj wssinit.obj
	link /MAP /TINY shell codec start wssinit, sndsys.com, sndsys;

codec.obj: 	codec.asm   ..\compat.inc 
	ml /c /Cp /I.. /Focodec   /Flcodec   codec.asm	

shell.obj:     	shell.asm   ..\compat.inc ..\soundrv.inc ..\prologue.mac 
	ml /c /Cp /I.. /Foshell   /Flshell   shell.asm	

start.obj:     	start.asm   ..\compat.inc ..\soundrv.inc ..\prologue.mac 
	ml /c /Cp /I.. /Fostart   /Flstart   start.asm	

wssinit.obj: 	wssinit.asm ..\compat.inc 
	ml /c /Cp /I.. /Fowssinit /Flwssinit wssinit.asm	

clean:
	-del *.obj
	-del *.map
	-del *.lst

cclean:	clean
	-del *.com
        