
gf1midi.adv: xmidi.asm mt32.inc mpu401.inc ..\ail.inc ..\ail.mac
   	ml /AT /Cp /DMT32 /DMPU401  /I.. /I..\GF1TSR /Fegf1midi.adv /Fogf1midi /Flgf1midi xmidi.asm

clean:
	del *.obj
	del *.adv
	del *.map
	del *.lst
