;----------------------------------------------------------------------------
;--                                                                        --
;--   SPKR.INC                                                             --
;--                                                                        --
;--   IBM Audio Interface Library -- Internal speaker support for PC/Tandy --
;--                                                                        --
;--   Version 1.00 of 27-Sep-91: Initial version for AIL V2.0 release      --
;--                                                                        --
;--   8086 ASM source compatible with Turbo Assembler v2.0 or later        --
;--   Author: John Miles                                                   --
;--                                                                        --
;--   DISASSEMBLED ROUTINES                                                --
;--                                                                        --
;----------------------------------------------------------------------------
;--                                                                        --
;--   Copyright (C) 1991, 1992 Miles Design, Inc.                          --
;--                                                                        --
;--   Miles Design, Inc.                                                   --
;--   10926 Jollyville #308                                                --
;--   Austin, TX 78759                                                     --
;--   (512) 345-2642 / FAX (512) 338-9630 / BBS (512) 454-9990             --
;--                                                                        --
;----------------------------------------------------------------------------
