
dmasound.adv: dmasound.asm ..\ail.inc ..\ail.mac ..\vol.inc ..\gf1tsr\ultmidi.inc
   	ml /AT /Cp /DSBSTD  /I.. /I..\GF1TSR /Fedmasound /Fodmasound /Fldmasound dmasound.asm
   	copy dmasound.com gf1digi.adv

clean:
	del *.obj
	del *.adv
	del *.map
	del *.lst
