#
# use nmake /I
#
all:
	cd ADVDIG
	-nmake	
	cd ..
	cd ADVMID
	-nmake
	cd ..
	cd DIGPAK
	nmake
	cd ..

clean:
	cd ADVDIG
	nmake clean	
	cd ..
	cd ADVMID
	nmake clean
	cd ..
	cd DIGPAK
	nmake clean
	cd ..

cclean:
	cd ADVDIG
	nmake cclean	
	cd ..
	cd ADVMID
	nmake cclean
	cd ..
	cd DIGPAK
	nmake cclean
	cd ..
