all:
	cd ADVDIG
	make	
	cd ..
	cd ADVMID
	make
	cd ..
	cd DIGPAK
	make
	cd ..

clean:
	cd ADVDIG
	make clean	
	cd ..
	
	cd ADVMID
	make clean
	cd ..
	cd DIGPAK
	make clean
	cd ..

cclean:
	cd ADVDIG
	make cclean	
	cd ..
	
	cd ADVMID
	make cclean
	cd ..
	cd DIGPAK
	make cclean
	cd ..
