
vector.com:      vector.asm ..\compat.inc ..\soundrv.inc ..\prologue.mac 
	ml /AT /Cp /I.. /Fevector /Fovector /Flvector /Fmvector vector.asm	

clean:
	-del *.obj
	-del *.map
	-del *.lst

cclean:	clean
	-del *.com
        